language: java
dist: trusty
group: edge
jdk: oraclejdk8
sudo: required # To ensure we get a VM rather than a container for more memory and for all the apt-get stuff

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.13.0
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: "MMzx2PxzjMuJL7S74SxL3ZWdGiOqBh/geLJJIftY9ReswLVvJbxurB0PDYvdPw8E/bJ7ykWjR99mLBi2K7FV+SavBTVXEwvw8T8AO9TQe7x5RkIQu+jeM2wf8KfABPUDrdA7PlbA8cVO9LAUTBMTJ6E7x4+3khpqjmBZGxRzTAECDyHKeHIioDfRFkZsnn5JzcoiUk1TLk8snubIL7mE0euVylSdYUPHUO7OWe7DNzoOuWcXOQmIwuhTIDeKSv5aGLuLVbILvvngzFhpdr28dsapAgvJZMBC6dfGJbb59/RH3M7rE+WIOVjb1+npDxWsuhE8rAYJZIb5id0BqxjVyPJl05g+zIe8FICrNgRlTYqgF4uxrR02AvEAf0mDAHd+KralBA9sz8Q/IBmw7sfkq+8jYslLOa1GA/DDXjWJ/KGZPmIxj3HaMjjepyOjO2LIZIItQ2XsoUPDxra5BAUU5c7InKJpEiFw9dlhfjlJBJE1QBowUgVmlrrYBSI92mB8dQlYyyPBUP2pz5RoqnpBjyLg5vccAzWFiI76fRXmCXuZz51GmT+e2p6ZFD5rQ+KiTqpWIdz8vQ1jt+nRS9ufDzNgYeR0cykNmYnaJJETdi+LcZQefZcRN+X/bJqy4vLsYxxDSMo2IwsUgr/knSwdt4ZdKK2cDla0HyeKnwFAzOs="

before_install:
    # Print out the current versions before we change them
  - docker --version
  - docker-compose --version
    # Remove the old docker version
  - sudo apt-get -y remove docker docker-engine
    # Extra stuff required for docker CE
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    # Add the apt repo for docker
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates curl software-properties-common docker-ce
  - docker --version
    # Remove the old docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install: echo "skip 'gradle assemble' step to speed up build"

before_script:
  # Increase the size of the heap
  - echo $JAVA_OPTS
  - export JAVA_OPTS=-Xmx1024m
  # Get stroom-resources and start the DBs
  - mkdir -p ../git_work
  - pushd ../git_work
  - git clone https://github.com/gchq/stroom-resources.git
  - pushd stroom-resources/dev-resources/compose/containers
  # Start all the services we need to run the integration tests in stroom
  - docker-compose -f stroomAnnotationsDb.yml up -d
  - popd
  - popd

# Use 1 local worker to avoid using too much memory as each worker will chew up ~500Mb ram
script: ./gradlew -Pversion=$TRAVIS_TAG clean build shadowJar

# Conditionally tag git and build docker image.
after_success:  "./.travis.after_success.sh"

# Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI: `$ travis setup releases`
deploy:
  provider: releases
  api_key:
    secure: J0xazmGXIi8IB6cajKd4AVBtSrmacvsV3RAA3ZJo8XsR/AkmHEDVH+HrCPwsg5kfKQXYX3f5o9KseVJMWGEaHzJyZVJmcPCrwMt5pqcctpUxl5mDQRH3oplaAiFDIe2JQbOrk1axnAeqcyBwxZF84RTDAwrKAoBDeGdaeqNpk/jZZNwfoGVpvYGza2gnhz6k2QbSuQa5Q1FOLxLdBS8pqkfNg4U4whzCzDhZdExh5Hob3gIaavIs0CANBT68ezKrc7wPDGkSvgo2frC7G2Qg7elfUky6PnT0d8p3Qt2q+ATijoBFOE7OP5nap2nI2zasugOuV31q/u4jX/q1ikYB1pOuCqrw+3bsrkklMB9KtCkKSWOaNnG2EAO5KYRlSPE2+CO1N+/YhjxGPOCAWIOsbN3sXjL/ARSliOsioWDxgp7llCxL09fWSV+owFwRTXz3RcmFLJcc1Vj/KdWczbtzvCJjFOiDe0lYZLUqIgaOY79JZ0R+X2co+Faqz0kwi7+6apWtmloGn044NwJf3T3bTI5W4RC/e/R93b8nv8j8469EAe8pLaJMoMmJTOXBxgErUIO4W0rhoMKn8Qj5ig9JvWmS1Pvfn3E/NJ+y4tRFsCM2pocR3FUDDESmEduSzOlxj//u6DyrXziF3aLdlh2Ua7koDSKJHfZN9tplsDp5sc4=
  file: stroom-annotations-svc/build/libs/stroom-annotations-service-all.jar
  skip_cleanup: true
  on:
    repo: gchq/stroom-annotations
    tags: true

# Clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

