language: java
dist: trusty
group: edge
jdk: oraclejdk8
sudo: required # To ensure we get a VM rather than a container for more memory and for all the apt-get stuff

services:
  - docker

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: p04UfQL9fsTU0jaTqcnjarh+gxsBJGGIXJUTLs1VOQ2jXsl4+ThDnaR+xfNKxeJx7jaLeidiaKF8Ax/kP8w7l79IiTtfPMOVH+oMJkWVKC81fd9M0g+N+0n5b9eXJImWRQppDd8VmFMCJX0XgFMIRSFjWfWNf3NIPKwir7jpdX9n6ZYZcULpOKX567qT8TZKbLsH/atGOWphEKwwlpkYdVBwnACxWcQ395UkbPo+57R5uH5FzDBM7X/TBByVCS7MburDjLlDXGw38YEMKwaFMx0bvuTMb8N1TCONuFHiCROoxzY2lvZNHbRKd2tbXhCA+9lbHtAvPMBFzE9p0LbuTegbxACd3xILteKfIZ52ZCoUQPJwItkCNHHM49l/kLD1Cz4dTjw9RnziqctAk3kvYDQ3dIUlr6GTQXiQ1Td55+77nKI2GcdFtIB5+JdM2W4KbR7e2shFvaoVHXIT9cskf1/F/8VpT8718KB91dm1CMvsrWb1pXgRmjLFNT8lMkKTAgOajHfQFfTI4/hQzQ6W/n+S3zfNzSBW6PccnS3iviqHd+9r/pkXQE6n20Rq8eez2yY2BZwGWgHP9PCVZTaAzr7cot0g8/djLQ2d/AAkqvqtDZQdyKhsTkY1E78pYOmyG6hit5UdSubEliIyONLsYU6DquBIGonznSTSqZhO+FU=

install: echo "skip 'gradle assemble' step to speed up build"

before_script: ./travis.before_script.sh

# Use 1 local worker to avoid using too much memory as each worker will chew up ~500Mb ram
script: ./travis.script.sh

# Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI: `$ travis setup releases`
deploy:
  provider: releases
  api_key:
    secure: pV5jnpOVnBAyUl+WF7TnmeUhWN3icz4Hjuv8QwpIV0qSOSjW0wNXZBgCKPY4pH6EgVdo84BChNO7tthivYhknZdk3rrE44dy2SDBwXuFyv3lPKr8ejzLLLOdFi6PlPOYrQLLusrYQxgTCa9gW8aCvzXS1QyCHqLy4DZYjqYozhsh2dnICHzFwKl4C3jayKxRHp2kx9RdJEK4erOf85twMfVKPCPO630dLUZoEjRadx6m6iZ4suwRsSxCZZOuFWMmsd70pSN04alPrp52nuCVeerEWmokqQiTVrNeHNX4iSMTvbXnI7qCYGRMqExcOoxwgAAoCc3M17BaN5S62HDbnDelAx8+x6dyMILoNj0UhV9hBbCr7O79NrHcHHTfyrrcuVvkNCYnRbSAlRHnrja/JTJ0yZUYfRN+0Jf+JgwBZkNBBOT0r0Ga6Ok8MklphE4fVk7pynVB6MkvZglFkZ4cAdbjQqELe22FDOgR2HYbef+SrziIhAduWob3kTMhq7XDmJuaKFQhz6hLcXJ9wAgNVw/AQZji5t+ihuDz5rBvVBt5jp0TZYWzv8JNbkOUMLyHO1DdwgB59a1TAUHIi/9ylu1x2m/PAfnf1QwwLWjEYVQcV44iE7sZXpPnthrvF6oK0eXLGXbOtgdYJLWIBYuOU09Eu5s3oh1jjMeY+PR6SNM=
    file: stroom-annotations-svc/build/libs/stroom-annotations-service-all.jar
  skip_cleanup: true
  on:
    repo: gchq/stroom-annotations
    tags: true

# Clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

