/*
 * This file is generated by jOOQ.
*/
package stroom.db.annotations.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import stroom.db.annotations.tables.AnnotationsHistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnotationsHistoryRecord extends UpdatableRecordImpl<AnnotationsHistoryRecord> implements Record8<Integer, String, String, String, String, String, String, ULong> {

    private static final long serialVersionUID = 499504860;

    /**
     * Setter for <code>annotations.annotations_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>annotations.annotations_history.operation</code>.
     */
    public void setOperation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.operation</code>.
     */
    public String getOperation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>annotations.annotations_history.annotationId</code>.
     */
    public void setAnnotationid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.annotationId</code>.
     */
    public String getAnnotationid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>annotations.annotations_history.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>annotations.annotations_history.assignTo</code>.
     */
    public void setAssignto(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.assignTo</code>.
     */
    public String getAssignto() {
        return (String) get(4);
    }

    /**
     * Setter for <code>annotations.annotations_history.content</code>.
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.content</code>.
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>annotations.annotations_history.updatedBy</code>.
     */
    public void setUpdatedby(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.updatedBy</code>.
     */
    public String getUpdatedby() {
        return (String) get(6);
    }

    /**
     * Setter for <code>annotations.annotations_history.lastUpdated</code>.
     */
    public void setLastupdated(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>annotations.annotations_history.lastUpdated</code>.
     */
    public ULong getLastupdated() {
        return (ULong) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, ULong> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, String, String, String, ULong> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.OPERATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.ANNOTATIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.ASSIGNTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.UPDATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field8() {
        return AnnotationsHistory.ANNOTATIONS_HISTORY.LASTUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOperation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAnnotationid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAssignto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value8() {
        return getLastupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value2(String value) {
        setOperation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value3(String value) {
        setAnnotationid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value5(String value) {
        setAssignto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value7(String value) {
        setUpdatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord value8(ULong value) {
        setLastupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsHistoryRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, ULong value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnnotationsHistoryRecord
     */
    public AnnotationsHistoryRecord() {
        super(AnnotationsHistory.ANNOTATIONS_HISTORY);
    }

    /**
     * Create a detached, initialised AnnotationsHistoryRecord
     */
    public AnnotationsHistoryRecord(Integer id, String operation, String annotationid, String status, String assignto, String content, String updatedby, ULong lastupdated) {
        super(AnnotationsHistory.ANNOTATIONS_HISTORY);

        set(0, id);
        set(1, operation);
        set(2, annotationid);
        set(3, status);
        set(4, assignto);
        set(5, content);
        set(6, updatedby);
        set(7, lastupdated);
    }
}
