/*
 * This file is generated by jOOQ.
*/
package stroom.db.annotations.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import stroom.db.annotations.tables.Annotations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnotationsRecord extends UpdatableRecordImpl<AnnotationsRecord> implements Record6<String, String, String, String, String, ULong> {

    private static final long serialVersionUID = -1968815868;

    /**
     * Setter for <code>annotations.annotations.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>annotations.annotations.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>annotations.annotations.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>annotations.annotations.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>annotations.annotations.assignTo</code>.
     */
    public void setAssignto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>annotations.annotations.assignTo</code>.
     */
    public String getAssignto() {
        return (String) get(2);
    }

    /**
     * Setter for <code>annotations.annotations.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>annotations.annotations.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>annotations.annotations.updatedBy</code>.
     */
    public void setUpdatedby(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>annotations.annotations.updatedBy</code>.
     */
    public String getUpdatedby() {
        return (String) get(4);
    }

    /**
     * Setter for <code>annotations.annotations.lastUpdated</code>.
     */
    public void setLastupdated(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>annotations.annotations.lastUpdated</code>.
     */
    public ULong getLastupdated() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, ULong> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, ULong> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Annotations.ANNOTATIONS_.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Annotations.ANNOTATIONS_.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Annotations.ANNOTATIONS_.ASSIGNTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Annotations.ANNOTATIONS_.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Annotations.ANNOTATIONS_.UPDATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return Annotations.ANNOTATIONS_.LASTUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAssignto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getLastupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value3(String value) {
        setAssignto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value5(String value) {
        setUpdatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord value6(ULong value) {
        setLastupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnnotationsRecord values(String value1, String value2, String value3, String value4, String value5, ULong value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnnotationsRecord
     */
    public AnnotationsRecord() {
        super(Annotations.ANNOTATIONS_);
    }

    /**
     * Create a detached, initialised AnnotationsRecord
     */
    public AnnotationsRecord(String id, String status, String assignto, String content, String updatedby, ULong lastupdated) {
        super(Annotations.ANNOTATIONS_);

        set(0, id);
        set(1, status);
        set(2, assignto);
        set(3, content);
        set(4, updatedby);
        set(5, lastupdated);
    }
}
