kafka:
  bootstrapServers: localhost:9092
  loggingTopic: logging

server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /}
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  applicationConnectors:
    - type: ${APPLICATION_CONNEXTOR_TYPE:- http}
      port: ${APPLICATION_CONNEXTOR_PORT:- 8199}
  adminConnectors:
    - type: ${ADMIN_CONNEXTOR_TYPE:- http}
      port: ${ADMIN_CONNEXTOR_PORT:- 8200}

database:
  driverClass: org.mariadb.jdbc.Driver
  user: ${DB_USER:- stroomuser}
  password: ${DB_PASSWORD:- stroompassword1}
  url: ${DB_URL:- jdbc:mariadb://localhost:3310/annotations}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.show_sql: false
    hibernate.hbm2ddl.auto: update

logging:
  level: ${LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

jooq:
  dialect: MYSQL
  logExecutedSql: yes
  renderSchema: yes
  renderNameStyle: QUOTED
  renderKeywordStyle: LOWER
  renderFormatted: no
  paramType: INDEXED
  statementType: PREPARED_STATEMENT
  executeLogging: no
  executeWithOptimisticLocking: no
  attachRecords: yes
  updatablePrimaryKeys: no