server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 10299
  adminConnectors:
    - type: http
      port: 10300


jwsIssuer: stroom
algorithm: RS256