/*
 * This file is generated by jOOQ.
*/
package stroom.db.annotations;


import javax.annotation.Generated;

import stroom.db.annotations.tables.Annotations;


/**
 * Convenience access to all tables in annotations
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>annotations.annotations</code>.
     */
    public static final Annotations ANNOTATIONS_ = stroom.db.annotations.tables.Annotations.ANNOTATIONS_;
}
